# Generated by Django 2.2 on 2020-12-15 12:35

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20201214_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='attach',
            field=models.FileField(blank=True, upload_to=course.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
